# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-06 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('city', models.CharField(max_length=50)),
                ('slug', models.SlugField(help_text=b'The URL piece that identifies this event, e.g. `cocktailsummit.com/spokane`')),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('day_one_blurb', models.TextField(blank=True)),
                ('day_two_blurb', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OffsiteSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('room', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktail_summit.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('room', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktail_summit.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to=b'')),
                ('affiliation', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to=b'')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('event', models.ManyToManyField(blank=True, to='cocktail_summit.Event')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='cocktail_summit.Speaker'),
        ),
        migrations.AddField(
            model_name='session',
            name='sponsor',
            field=models.ManyToManyField(blank=True, to='cocktail_summit.Sponsor'),
        ),
        migrations.AddField(
            model_name='offsitesession',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='cocktail_summit.Speaker'),
        ),
        migrations.AddField(
            model_name='offsitesession',
            name='sponsor',
            field=models.ManyToManyField(blank=True, to='cocktail_summit.Sponsor'),
        ),
    ]
