# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-12 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_summit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffsiteEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('room', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='speaker',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='session',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='session',
            name='sponsor',
            field=models.ManyToManyField(blank=True, to='cocktail_summit.Sponsor'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='affiliation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='offsiteevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktail_summit.Event'),
        ),
        migrations.AddField(
            model_name='offsiteevent',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='cocktail_summit.Speaker'),
        ),
        migrations.AddField(
            model_name='offsiteevent',
            name='sponsor',
            field=models.ManyToManyField(blank=True, to='cocktail_summit.Sponsor'),
        ),
    ]
